// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/create-room.tsx";
import * as $3 from "./routes/faq.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/join-room.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Room.tsx";
import * as $$2 from "./islands/create-room-form.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/create-room.tsx": $2,
    "./routes/faq.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/join-room.tsx": $5,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/Room.tsx": $$1,
    "./islands/create-room-form.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
