// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/create-room.tsx";
import * as $4 from "./routes/faq.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/join-room.tsx";
import * as $7 from "./routes/room/create/[key]/[username].tsx";
import * as $8 from "./routes/room/join/[key]/[username].tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Hamburger.tsx";
import * as $$2 from "./islands/Messages.tsx";
import * as $$3 from "./islands/Room.tsx";
import * as $$4 from "./islands/ThemeSwitcher.tsx";
import * as $$5 from "./islands/VerifiedInput.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/create-room.tsx": $3,
    "./routes/faq.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/join-room.tsx": $6,
    "./routes/room/create/[key]/[username].tsx": $7,
    "./routes/room/join/[key]/[username].tsx": $8,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/Hamburger.tsx": $$1,
    "./islands/Messages.tsx": $$2,
    "./islands/Room.tsx": $$3,
    "./islands/ThemeSwitcher.tsx": $$4,
    "./islands/VerifiedInput.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
